config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
  end

  def create
    @todo = Todo.new
    @todo[:title] = params[:todo][:title]
    @todo[:task] = params[:todo][:task]
    @todo[:name] = params[:todo][:name]
    @todo.save
    redirect_to todo_path(@todo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Your Tasks:</h1>

<% @todos.each do |todo| %>
  <div><%= link_to todo.title, todo_path(todo) %> | <%= todo.name %></div>
<% end %><br>

<%= link_to "Create a New task", new_todo_path %>

app/views/todos/new.html.erb
<h1>Todo List Form:</h1>

<%= form_tag todos_path do %>

    <label>Name:</label><br>
    <%= text_field_tag :'todo[name' %><br><br>

    <label>Title:</label><br>
    <%= text_field_tag :'todo[title]' %><br><br>

    <label>Task:</label><br>
    <%= text_area_tag :'todo[task]' %><br><br>

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= submit_tag "Submit Task" %><br><br>

    <%= link_to "View all tasks", todos_path %>

<% end %>

app/views/todos/show.html.erb
<h2>Title: <%= @todo.title %> </h2><br>
<h3>Task:</h3>
<%= @todo.task %>
<h3>Name:</h3>
<%= @todo.name %><br><br>

<%= link_to "Back", :back %>